### ISSUE TITLE
export xml to json error

### ISSUE THREAD

**Issue by Axxon** [philipmat/discogs-xml2db#97]
Hello, (thx to share this code:), i try to run `./discogsparser.py -i -o mongo -p "file:///tmp/discogs/?uniq=md5" -d 20200401` but this error appear:
```sh
Traceback (most recent call last):
  File "discogsparser.py", line 139, in <module>
    main(sys.argv[1:])
  File "discogsparser.py", line 128, in main
    exporter = make_exporter(options)
  File "/srv/exporters/__init__.py", line 27, in make_exporter
    m = __import__('.'.join(parts[:-1]))
  File "/srv/exporters/mongodbexporter.py", line 3, in <module>
    from jsonexporter import jsonizer as _jsonizer
ModuleNotFoundError: No module named 'jsonexporter'

```
I not a familiar with Python, so sorry but i can't debug myself directly, i'll try today, do you have a idea please?

```sh
python --version
Python 3.6.10
```

**Comment by Axxon** [comment]
Okay in mongodbexporter.py:3 a dot is missing so .jsonexporter instead. Now i have another dependency that not match: urlparse. not found with pip.. i search

**Comment by Axxon** [comment]
`discogs-xml2db works with Python 2.7 and 3.6.` > no :) urlparse = urllib.parse as urlparse.

**Comment by Axxon** [comment]
I retrograde to py 2.7 but now it generate empty .json files (artists.json, labels.json, masters.json, releases.json).

**Comment by Axxon** [comment]
ok finally, i tried again with 3.6 cause in 2.7:
```
root@60e580199c25:/srv# python discogsparser.py -i -o mongo "file:///srv/data/?uniq=md5" -d 20200401
Traceback (most recent call last):
  File "discogsparser.py", line 144, in <module>
    main(sys.argv[1:])
  File "discogsparser.py", line 132, in main
    exporter = make_exporter(options)
  File "/srv/exporters/__init__.py", line 32, in make_exporter
    return m(options.params, data_quality=data_quality)
  File "/srv/exporters/mongodbexporter.py", line 151, in __init__
    self.connect(mongo_uri)
  File "/srv/exporters/mongodbexporter.py", line 157, in connect
    u = urlparse.urlparse(mongo_uri)
  File "/usr/local/lib/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/local/lib/python2.7/urlparse.py", line 201, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
root@60e580199c25:/srv# python discogsparser.py -i -o mongo "file:///data/?uniq=md5" -d 20200401
Traceback (most recent call last):
  File "discogsparser.py", line 144, in <module>
    main(sys.argv[1:])
  File "discogsparser.py", line 132, in main
    exporter = make_exporter(options)
  File "/srv/exporters/__init__.py", line 32, in make_exporter
    return m(options.params, data_quality=data_quality)
  File "/srv/exporters/mongodbexporter.py", line 151, in __init__
    self.connect(mongo_uri)
  File "/srv/exporters/mongodbexporter.py", line 157, in connect
    u = urlparse.urlparse(mongo_uri)
  File "/usr/local/lib/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/local/lib/python2.7/urlparse.py", line 201, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
```
The xml to json seems to work (the command in under run).

**Comment by Axxon** [comment]
so in 3.6.10
```
Python 3.6.10 (default, Apr 23 2020, 15:24:07) 
[GCC 8.3.0] on linux
>>> runfile('/srv/discogsparser.py', args=['-i', '-o', 'mongo', '-p', 'file:///srv/data/?uniq=md5', '-d', '20200401'], wdir='/srv')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/opt/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/opt/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/srv/discogsparser.py", line 144, in <module>
    main(sys.argv[1:])
  File "/srv/discogsparser.py", line 138, in main
    parseMasters(parser, exporter)
  File "/srv/discogsparser.py", line 98, in parseMasters
    parseEntities(parser, exporter, 'masters', MasterHandler)
  File "/srv/discogsparser.py", line 76, in parseEntities
    parser.parse(f)
  File "/usr/local/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/local/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/src/python/Modules/pyexpat.c", line 473, in EndElement
  File "/usr/local/lib/python3.6/xml/sax/expatreader.py", line 336, in end_element
    self._cont_handler.endElement(name)
  File "/srv/parsers/discogsmasterparser.py", line 173, in endElement
    self.exporter.storeMaster(self.master)
  File "/srv/exporters/mongodbexporter.py", line 260, in storeMaster
    self.execute('masters', master)
  File "/srv/exporters/mongodbexporter.py", line 208, in execute
    uniq, md5 = self._is_uniq(collection, what.id, json_string)
  File "/srv/exporters/mongodbexporter.py", line 186, in _is_uniq
    return self._quick_uniq.is_uniq(collection, id, json_string)
  File "/srv/exporters/mongodbexporter.py", line 114, in is_uniq
    new_md5 = md5(self._one_line(json_string)).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

Try to fix files with fix-xml.py, but:
```
>>> runfile('/srv/fix-xml.py', args=['20200401'], wdir='/srv')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/opt/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/opt/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/srv/fix-xml.py", line 5, in <module>
    from contextlib import nested
ImportError: cannot import name 'nested'
```
Not the right contextlib version ? The story continue ..

**Comment by Axxon** [comment]
https://docs.python.org/2/library/contextlib.html > contextlib has nested in 2.7 not in 3...

**Comment by Axxon** [comment]
I fixed the nested issue with:
```py
from contextlib import ExitStack, contextmanager

@contextmanager
def nested(*contexts):
    """
    Reimplementation of nested in python 3.
    """
    with ExitStack() as stack:
        for ctx in contexts:
            stack.enter_context(ctx)
        yield contexts
```

but now:
```
>>> runfile('/srv/fix-xml.py', args=['20200401'], wdir='/srv')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/opt/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/opt/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/srv/fix-xml.py", line 78, in <module>
    main(sys.argv[1:])
  File "/srv/fix-xml.py", line 65, in main
    clean(filename)
  File "/srv/fix-xml.py", line 31, in clean
    rObj = re.search(ctrlregex, line)
  File "/usr/local/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```
Damn. so now i imagine it was developed with 2.7 and the `AttributeError: 'NoneType' object has no attribute 'find'` on py 2.7 should be fixed. Maybe the content xml was not cleaned before i give it the discogsparer.py.

**Comment by Axxon** [comment]
Okay i was on the right way it's 2.7 only compatible. (until you prove me the inverse :). So the fix work. But now :/
```sh
root@a6c45ff0686d:/srv/data# python ../discogsparser.py -i -o mongo -p "file:///srv/data/?uniq=md5" -d 20200401
Traceback (most recent call last):
  File "../discogsparser.py", line 144, in <module>
    main(sys.argv[1:])
  File "../discogsparser.py", line 135, in main
    parseArtists(parser, exporter)
  File "../discogsparser.py", line 83, in parseArtists
    parseEntities(parser, exporter, 'artists', ArtistHandler)
  File "../discogsparser.py", line 76, in parseEntities
    parser.parse(f)
  File "/usr/local/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/local/lib/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/local/lib/python2.7/xml/sax/expatreader.py", line 339, in end_element
    self._cont_handler.endElement(name)
  File "/srv/parsers/discogsartistparser.py", line 106, in endElement
    self.exporter.storeArtist(self.artist)
  File "/srv/exporters/mongodbexporter.py", line 248, in storeArtist
    self.execute('artists', artist)
  File "/srv/exporters/mongodbexporter.py", line 214, in execute
    self._store+_processed(collection, what.id, md5)
AttributeError: 'MongoDbExporter' object has no attribute '_store'
```
Don't give it up !

**Comment by Axxon** [comment]
After the fix command it seems to work. It's under process. Conclusion it's only work on 2.7.

**Comment by berz** [comment]
You are right, the current version of discogs-xml2db requires python 2. I am glad you got it to work.

You might be interested to learn that there is a new version of the code available in the `speedup/` directory. This code uses a faster aproach than the current code and is written in python 3. I do not use it with mongo myself but it should work this way:

- download the latest dumps into a directory (you can leave these zipped if you want)
- install dependencies: `pip install -r discogs-xml2db/speedup/requirements.txt`
- create csv files based on the discogs label, artist, release and masters xml files: `python3 discogs-xml2db/speedup/exporter.py --export label --export artist --export release --export master XMLDIR/ CSVDIR/`
- import the csv files into mongdb using [mongoimport](https://docs.mongodb.com/manual/reference/program/mongoimport/).  
 for example: `mongoimport --db=discogs --type=csv --headerline --file=CSVDIR/release.csv`

**Comment by Axxon** [comment]
Thank you very much for this advices, i'll try it. Now i'm waking up with a cofee, i'll try mongo import in a second. I let my computerr convert json all night long. So here we go. When everything will work maybe you should be interested that i pull on a fork my docker-compose for this project.
