### ISSUE TITLE
ImportError: cannot import name zip_longest

### ISSUE THREAD

**Issue by Zebra447** [philipmat/discogs-xml2db#115]
I'm getting this error when trying to export on CentOs 8 ... can't find a solution on google :(

[root@server discogs-xml2db]# python run.py --export artist --bz2
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    from discogsxml2db.exporter import main
  File "/var/www/vhosts/x.net/discogs-xml2db/discogsxml2db/exporter.py", line 10, in <module>
    from .parser import DiscogsArtistParser, DiscogsLabelParser, DiscogsMasterParser, DiscogsReleaseParser
  File "/var/www/vhosts/x.net/discogs-xml2db/discogsxml2db/parser.py", line 2, in <module>
    from itertools import zip_longest
ImportError: cannot import name zip_longest

**Comment by philipmat** [comment]
Please post the output of the following commands:

* `git show --oneline -s` (execute in the same directory as run.py)
* `python -V`
* `python -c "import itertools; dir(itertools)"`

**Comment by Zebra447** [comment]
Thanks for the reply,

Here is the result of the commands

[root@server discogs-xml2db]# git show --oneline -s
fatal: not a git repository (or any of the parent directories): .git
[root@server discogs-xml2db]# python -V
Python 2.7.17
[root@server discogs-xml2db]# python -c "import itertools; dir(itertools)"
[root@server discogs-xml2db]#

I didn't install xml2db with git, I just downloaded the zip and uploaded it to my server.

**Comment by philipmat** [comment]
Develop currently contains the speed up version, which requires python 3.6 at a minimum.

Master and tag v1.99 still contain a version that works with python 2.7, thought it's the slower variant. Also no longer maintained.

**Comment by Ungov77** [comment]
I also tried with Puthon 3.6 but I get another error

[root@server discogs-xml2db]# python3 run.py \ --bz2 --export artist
Processing     artists:   0%|                                                                       | 0/5000000 [00:00<?, ?artists/s]
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    sys.exit(main(arguments))
  File "/var/www/vhosts/punkmusic.net/discogs-xml2db/discogsxml2db/exporter.py", line 325, in main
    exporter.export()
  File "/var/www/vhosts/punkmusic.net/discogs-xml2db/discogsxml2db/exporter.py", line 71, in export
    return self.export_from_file(self.openfile())
  File "/var/www/vhosts/punkmusic.net/discogs-xml2db/discogsxml2db/exporter.py", line 123, in export_from_file
    for cnt, entity in enumerate(filter(self.validate, self.parser.parse(fp)), start=1):
  File "/var/www/vhosts/punkmusic.net/discogs-xml2db/discogsxml2db/parser.py", line 83, in parse
    for event, element in etree.iterparse(fp, tag=self.entity_tag):
  File "src/lxml/iterparse.pxi", line 78, in lxml.etree.iterparse.__init__
TypeError: expected str, bytes or os.PathLike object, not NoneType
[root@server discogs-xml2db]#

**Comment by philipmat** [comment]
You forgot to pass the input folder as parameter. Also the output folder.
